name: build & upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.15.x]
        #[macos,ubuntu, windows]
        os: [macos]
        onf-version: [v0.1.0]
    runs-on:  ${{ matrix.os }}-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - name: version check
      uses: marceloprado/has-changed-path@v1
      id: version
      with:
        paths: ./VERSION

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: read version
      uses: pCYSl5EDgo/cat@master
      id: onf-version
      with:
        path: VERSION
    
    - name: onf upgrade
      uses: "454076513/action-onf-release@latest"
      with:
        onf-access-key: "${{ secrets.ONF_ACCESS_KEY }}"
        onf-secret-key: "${{ secrets.ONF_SECRET_KEY }}"
        onf-workspace-id: "${{ secrets.ONF_WORKSPACE_ID }}"
        onf-network-key: 28501c77-e3ba-4d24-8bb8-32a00075e29d
        onf-sub_command: node
        onf-action: upgrade
        image-version: ${{ steps.onf-version.outputs.text }}
        percent: 30


    
    
    
    
    
    
    
    